name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t dmkarpiy/skypro_lesson_docker_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_NAME }} --password-stdin
      - name: docker push
        run: docker push dmkarpiy/skypro_lesson_docker_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
       uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml 
          cat dcoekr_ci_config.py | envsubst > deploy/docker-config.yaml
      - name: copy files to server
        uses: appleboy/scp-action@master
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "deploy/docker-compose.yaml,deploy/docker-config.yaml"
        target: "flask_app_ci"
        strip_comments: 1


